bracketSameLine: true
bracketSpacing: true
singleQuote: true
htmlWhitespaceSensitivity: ignore
trailingComma: all
semi: true
tabWidth: 2
useTabs: false
plugins:
  - prettier-plugin-organize-attributes
  - prettier-plugin-organize-imports
  - prettier-plugin-tailwindcss
